# Generated by Django 4.0.10 on 2023-11-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_question',
            name='answer',
            field=models.CharField(max_length=255),
        ),
    ]
