# Generated by Django 4.0.10 on 2023-11-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_exam_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_question',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
